### ISSUE TITLE
To-do Tracker

### ISSUE THREAD

**Issue by NiceAesth** [SunnyCord/DifficultyAttributeService#1]
Broken due to https://github.com/ppy/osu/issues/15328 which causes slider velocities to be missed during calculation.
Depends on: https://github.com/ppy/osu/pull/25131

- [x] Async
- [ ] Add Sentry logging
- [ ] Add automated docker builds
- [ ] Add CI against `aiosu`
- [ ] Add automatic updating for osu! versions (depends on CI checks)
